// src/components/CollectionTree.tsx
import { methodClass, ROOT_ID } from '../lib/collectionTree'
import type { ApiFolder, ApiRequest, Collection } from '../tauri'

type CollectionTreeProps = {
  collections: Collection[]
  foldersByParent: Map<string, ApiFolder[]>
  handleDeleteCollection: (collection: Collection) => Promise<void>
  handleRenameCollection: (collection: Collection) => Promise<void>
  loadingRequests: boolean
  openFolderIds: Set<string>
  requestsByFolder: Map<string, ApiRequest[]>
  selectedCollectionId: string | null
  selectedRequestId: string | null
  setSelectedCollectionId: (id: string | null) => void
  setSelectedRequestId: (id: string | null) => void
  toggleFolder: (folderId: string) => void
}

export default function CollectionTree({
  collections,
  foldersByParent,
  handleDeleteCollection,
  handleRenameCollection,
  loadingRequests,
  openFolderIds,
  requestsByFolder,
  selectedCollectionId,
  selectedRequestId,
  setSelectedCollectionId,
  setSelectedRequestId,
  toggleFolder,
}: CollectionTreeProps) {
  function renderRequestRow(request: ApiRequest, depth = 0) {
    return (
      <button
        key={request.id}
        onClick={() => setSelectedRequestId(request.id)}
        className={`flex h-7 w-full items-center gap-2 rounded px-2 text-left text-xs ${
          request.id === selectedRequestId
            ? 'bg-[var(--surface)] text-[var(--text)]'
            : 'text-[var(--muted)] hover:bg-[var(--panel)]'
        }`}
        style={{ paddingLeft: `${8 + depth * 14}px` }}
      >
        <span className={`w-12 shrink-0 font-semibold ${methodClass(request.method)}`}>
          {request.method}
        </span>
        <span className="min-w-0 flex-1 truncate">{request.name}</span>
      </button>
    )
  }

  function renderFolder(folder: ApiFolder, depth = 0) {
    const isOpen = openFolderIds.has(folder.id)
    const childFolders = foldersByParent.get(folder.id) ?? []
    const childRequests = requestsByFolder.get(folder.id) ?? []

    return (
      <div key={folder.id}>
        <button
          className="flex h-7 w-full items-center gap-2 rounded px-2 text-left text-xs text-[#d8d8d8] hover:bg-[#303030]"
          onClick={() => toggleFolder(folder.id)}
          style={{ paddingLeft: `${8 + depth * 14}px` }}
        >
          <span className="w-3 shrink-0 text-[var(--muted)]">{isOpen ? 'v' : '>'}</span>
          <span className="min-w-0 flex-1 truncate">{folder.name}</span>
        </button>
        {isOpen ? (
          <div className="space-y-1">
            {childFolders.map((child) => renderFolder(child, depth + 1))}
            {childRequests.map((request) => renderRequestRow(request, depth + 1))}
          </div>
        ) : null}
      </div>
    )
  }

  return (
    <>
      {collections.map((collection) => {
        const expanded = collection.id === selectedCollectionId
        const rootFolders = foldersByParent.get(ROOT_ID) ?? []
        const rootRequests = requestsByFolder.get(ROOT_ID) ?? []

        return (
          <div key={collection.id} className="mb-1">
            <div className={`group flex h-8 w-full items-center gap-2 rounded px-2 text-left text-sm ${expanded ? 'bg-[var(--surface)] text-[var(--text)]' : 'text-[var(--muted)] hover:bg-[var(--panel)]'}`}>
              <button className="flex min-w-0 flex-1 items-center gap-2 text-left" onClick={() => setSelectedCollectionId(collection.id)}>
                <span className="w-3 shrink-0 text-[var(--muted)]">{expanded ? 'v' : '>'}</span>
                <span className="min-w-0 flex-1 truncate">{collection.name}</span>
              </button>
              <button className="rounded px-1 text-[11px] text-[var(--muted)] opacity-0 hover:bg-[var(--panel)] group-hover:opacity-100" onClick={() => handleRenameCollection(collection)}>Rename</button>
              <button className="rounded px-1 text-[11px] text-[var(--muted)] opacity-0 hover:bg-[var(--panel)] group-hover:opacity-100" onClick={() => handleDeleteCollection(collection)}>Delete</button>
            </div>

            {expanded ? (
              <div className="ml-3 mt-1 space-y-1">
                {loadingRequests ? (
                  <p className="py-2 text-xs text-[var(--muted)]">Loading requests...</p>
                ) : rootFolders.length === 0 && rootRequests.length === 0 ? (
                  <p className="py-2 text-xs text-[var(--muted)]">No requests yet.</p>
                ) : (
                  <>
                    {rootFolders.map((folder) => renderFolder(folder))}
                    {rootRequests.map((request) => renderRequestRow(request))}
                  </>
                )}
              </div>
            ) : null}
          </div>
        )
      })}
    </>
  )
}

// src/components/CollectionTree.svelte
<script lang="ts">
  import FolderNode from './FolderNode.svelte'
  import { methodClass, ROOT_ID } from '../lib/collectionTree'
  import type { ApiFolder, ApiRequest, Collection } from '../tauri'

  export let collections: Collection[]
  export let foldersByParent: Map<string, ApiFolder[]>
  export let handleDeleteCollection: (collection: Collection) => Promise<void>
  export let handleRenameCollection: (collection: Collection) => Promise<void>
  export let loadingRequests: boolean
  export let openFolderIds: Set<string>
  export let requestsByFolder: Map<string, ApiRequest[]>
  export let selectedCollectionId: string | null
  export let selectedRequestId: string | null
  export let setSelectedCollectionId: (id: string | null) => void
  export let setSelectedRequestId: (id: string | null) => void
  export let toggleFolder: (folderId: string) => void

  $: rootFolders = foldersByParent.get(ROOT_ID) ?? []
  $: rootRequests = requestsByFolder.get(ROOT_ID) ?? []
</script>

{#each collections as collection (collection.id)}
  {@const expanded = collection.id === selectedCollectionId}
  <div class="mb-1">
    <div class={`group flex h-8 w-full items-center gap-2 rounded px-2 text-left text-sm ${expanded ? 'bg-[var(--surface)] text-[var(--text)]' : 'text-[var(--muted)] hover:bg-[var(--panel)]'}`}>
      <button class="flex min-w-0 flex-1 items-center gap-2 text-left" on:click={() => setSelectedCollectionId(collection.id)}>
        <span class="w-3 shrink-0 text-[var(--muted)]">{expanded ? 'v' : '>'}</span>
        <span class="min-w-0 flex-1 truncate">{collection.name}</span>
      </button>
      <button class="rounded px-1 text-[11px] text-[var(--muted)] opacity-0 hover:bg-[var(--panel)] group-hover:opacity-100" on:click={() => handleRenameCollection(collection)}>Rename</button>
      <button class="rounded px-1 text-[11px] text-[var(--muted)] opacity-0 hover:bg-[var(--panel)] group-hover:opacity-100" on:click={() => handleDeleteCollection(collection)}>Delete</button>
    </div>

    {#if expanded}
      <div class="ml-3 mt-1 space-y-1">
        {#if loadingRequests}
          <p class="py-2 text-xs text-[var(--muted)]">Loading requests...</p>
        {:else if rootFolders.length === 0 && rootRequests.length === 0}
          <p class="py-2 text-xs text-[var(--muted)]">No requests yet.</p>
        {:else}
          {#each rootFolders as folder (folder.id)}
            <FolderNode
              {folder}
              depth={0}
              {foldersByParent}
              {requestsByFolder}
              {openFolderIds}
              {selectedRequestId}
              {setSelectedRequestId}
              {toggleFolder}
            />
          {/each}
          {#each rootRequests as request (request.id)}
            <button
              on:click={() => setSelectedRequestId(request.id)}
              class={`flex h-7 w-full items-center gap-2 rounded px-2 text-left text-xs ${
                request.id === selectedRequestId
                  ? 'bg-[var(--surface)] text-[var(--text)]'
                  : 'text-[var(--muted)] hover:bg-[var(--panel)]'
              }`}
              style="padding-left: 8px"
            >
              <span class={`w-12 shrink-0 font-semibold ${methodClass(request.method)}`}>
                {request.method}
              </span>
              <span class="min-w-0 flex-1 truncate">{request.name}</span>
            </button>
          {/each}
        {/if}
      </div>
    {/if}
  </div>
{/each}
